FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel

#FROM pytorch/pytorch

LABEL name="jason"

RUN apt-get update && apt-get install -y xz-utils vim tcpdump


#COPY requirements.txt /requirements.txt
#WORKDIR /


#RUN pip install -r ./requirements.txt

EXPOSE 80

#CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=80", "--no-browser", "--allow-root", "--NotebookApp.token=''"]

#https://www.youtube.com/watch?v=jtBVppyfDbE


